n1 = input("Digite o primeiro número: ")
n2 = input("Digite o segundo número: ")
soma = int(n1) + int(n2)
subtracao = int(n1) - int(n2)
multiplicacao = int(n1) * int(n2)
divisao = int(n1) / int(n2)
print("A soma dos números é: ", soma)
print("A subtração dos números é: ", subtracao)
print("A multiplicação dos números é: ", multiplicacao)
print("A divisão dos números é: ", divisao)